#!/bin/sh
# Generate /etc/dae/local.dae from UCI. Subscription URLs stay 0600.
# Only role=nodes entries go into subscription {}; complete Mihomo YAML
# subscriptions are consumed by kdae-sync.sh / dae-rule-sync.
# config.dae should include { local.dae }.

set -eu

CONF="/etc/dae/local.dae"
CFG=$(uci -q get dae.config.config_file || echo /etc/dae/config.dae)
TMP="${CONF}.tmp.$$"

lan=$(uci -q get dae.config.lan_interface || true)
wan=$(uci -q get dae.config.wan_interface || true)
listen=$(uci -q get dae.config.admin_listen || true)
secret=$(uci -q get dae.config.admin_secret || true)

quote_dae() {
	printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

sanitize_tag() {
	tag=$1
	printf '%s' "$tag" | grep -Eq '^[A-Za-z_][A-Za-z0-9_-]*$' || return 1
	return 0
}

persist_url() {
	url=$1
	persist=$2
	if [ "$persist" != "1" ]; then
		printf '%s' "$url"
		return
	fi
	case "$url" in
	https-file://*|http-file://*|file://*)
		printf '%s' "$url"
		;;
	https://*)
		printf 'https-file://%s' "${url#https://}"
		;;
	http://*)
		printf 'http-file://%s' "${url#http://}"
		;;
	*)
		printf '%s' "$url"
		;;
	esac
}

umask 077
{
	echo "# generated by luci-app-kdae; do not edit"
	echo "global {"
	if [ -n "$lan" ]; then
		echo "    lan_interface: ${lan}"
	fi
	if [ -n "$wan" ]; then
		echo "    wan_interface: ${wan}"
	fi
	if [ -n "$listen" ]; then
		echo "    admin_listen: '${listen}'"
	fi
	if [ -n "$secret" ]; then
		echo "    admin_secret: '${secret}'"
	fi
	echo "}"

	index=0
	count=0
	opened=0
	while uci -q get "dae.@subscription[$index]" >/dev/null 2>&1; do
		tag=$(uci -q get "dae.@subscription[$index].tag" || true)
		url=$(uci -q get "dae.@subscription[$index].url" || true)
		persist=$(uci -q get "dae.@subscription[$index].persist" || echo 1)
		role=$(uci -q get "dae.@subscription[$index].role" || true)
		index=$((index + 1))
		[ -n "$url" ] || continue
		case "$role" in
		""|routing)
			# Complete Mihomo YAML is fetched by dae-rule-sync, not kdae subscription {}.
			continue
			;;
		nodes)
			;;
		*)
			echo "invalid subscription role: $role" >&2
			exit 1
			;;
		esac
		count=$((count + 1))
		if [ -z "$tag" ]; then
			tag="sub${count}"
		fi
		if ! sanitize_tag "$tag"; then
			echo "invalid subscription tag: $tag" >&2
			exit 1
		fi
		if [ "$opened" -eq 0 ]; then
			echo
			echo "subscription {"
			opened=1
		fi
		stored=$(persist_url "$url" "$persist")
		echo "    ${tag}: $(quote_dae "$stored")"
	done
	if [ "$opened" -eq 1 ]; then
		echo "}"
	fi
} > "$TMP"
mv "$TMP" "$CONF"
chmod 0600 "$CONF"

if [ -f "$CFG" ] && ! grep -q 'local.dae' "$CFG"; then
	echo "warning: $CFG does not include local.dae; add: include { local.dae }" >&2
fi
